apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongo-deployment
spec:
    replicas: 1 # number of different pods described with the template spec
    selector:
        matchLabels:
            component: db
    template: # configuration for every single pod that is configured by this Deployment
        metadata:
            labels:
                component: db
        spec:
            containers:
                - name: test-mongo
                  image: mongo
                  ports:
                      - containerPort: 27017
