apiVersion: v1

kind: Service
metadata:
    name: webapp-network
spec:
    type: NodePort
    ports:
        - port: 3000
          targetPort: 3000
          nodePort: 31516
    selector:
        component: web
