---
- name: Initialize and setup Kubernetes cluster
  hosts: masters
  remote_user: kubenode
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
    - name: Initialize Kubernetes cluster
      command: kubeadm init --pod-network-cidr=192.168.1.0/24 --apiserver-advertise-address=192.168.0.13
      run_once: true

    - pause: seconds=30

    - name: Create directory for kube config
      become_user: kubenode
      become_method: sudo
      become: yes
      file:
        path: /home/kubenode/.kube
        state: directory
        owner: "kubenode"
        group: "kubenode"
        mode: 0755

    - name: Copy admin.conf to .kube/config
      become_user: root
      become_method: sudo
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kubenode/.kube/config
        remote_src: yes
        owner: "kubenode"
        group: "kubenode"
        mode: 0644

    - name: Remove the cache directory
      become_user: kubenode
      become_method: sudo
      become: yes
      file: 
        path: /home/kubenode/.kube/cache
        state: absent
    
    - name: Create Pod Network
      become_user: kubenode
      become_method: sudo
      become: yes
      command: "{{ item }}"
      with_items:
        - kubectl create -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml

    - name: Get the token for joining nodes to the cluster
      shell: kubeadm token create --print-join-command
      register: kubernetes_join_command

    - debug:
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Create tmp folder to store temporary files
      delegate_to: localhost
      file:
        path: tmp
        state: directory

    - name: Copy join command to local file.
      delegate_to: localhost
      copy:
        content: "{{ kubernetes_join_command.stdout_lines[0] }}"
        dest: tmp/kubernetes_join_command
        mode: 0777