---
- name: Join workers to Kubernetes cluster
  hosts: workers
  remote_user: kubenode
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
    - name: Copy join command to worker nodes
      copy:
        src: tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 0777

    - name: Join the worker nodes to the cluster
      command: sh /tmp/kubernetes_join_command
      register: joined_or_not

    - debug:
        msg: "{{ joined_or_not.stdout }}"